### ISSUE TITLE
Why did you create this?

### ISSUE THREAD

**Issue by yairEO** [Soontao/cycle-import-check#118]
[DPDM](https://www.npmjs.com/package/dpdm) is already the de-facto tool.

What were the reasons you've invested your time creating something that already exists and works very well?

**Comment by Soontao** [comment]
Hi @yairEO 

Haha, thats a historic question, in a short, when I created this tool, I did not search on npm just have a look into eslint, then I see, ok, no plugin/rule for dependency check, then this tool created. easy ?

Compare the value of this tool in my work, I would like to say its make sense, but you're right, if I knew the tool mentioned in that time point, I'll prefer to contribute to the existed one :)

Best Regards,
Theo

**Comment by yairEO** [comment]
But `eslint` have a rule for dependency check. For a long time...

https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md

Well, you could have Googled this in 2 minutes, instead of spending many days/weeks on this tool :)
