### ISSUE TITLE
[BUG] False positive on `this file import itself` when importing lib with same name as file

### ISSUE THREAD

**Issue by rafaeleyng** [Soontao/cycle-import-check#126]
## Describe the bug

When a file named `x.ts` imports a library called `x`, it recognizes that as a self-import.

This doesn't happen when a file `x.ts` imports another file `../other-folder/x.ts`.

It also happens within a longer cycle: file `x.ts` imports `y.ts`, and `y.ts` imports a library `x`.

## System Environment

* OS: Ubuntu 22.04
* Node Version: v.18.12.1
* This Library Version: 1.3.2

## To Reproduce

![image](https://user-images.githubusercontent.com/4842605/222175186-cb22d7cf-8fb6-4825-bc78-4ae713d59c0b.png)

## Expected behavior
The false positive should not happen.

## Additional context
None.

**Comment by Soontao** [comment]
a new version `1.4.0` will be released for this fix.
