### ISSUE TITLE
[Question] [Help wanted] This experimental syntax requires enabling one of the following parser plugin(s): "decorators-legacy", "decorators".

### ISSUE THREAD

**Issue by guohai** [Soontao/cycle-import-check#16]
## System Environment

* OS: Darwin Kernel Version 21.4.0
* NodeJS Version: v14.18.2
* This LIbrary Version: 1.2.3

## Question Description

> add some question description here
I met issues below, I'm wondering how can fix this issue. Thanks

# guohai@Hais-MacBook-Pro in ~/Dev/source/ts_example/app on git:dev/new_rn_packer x [22:13:31]
$ npx cycle-import-check .
Circular dependency checker running at ~/Dev/source/ts_example/app
Error while parsing /Users/guohai/Dev/source/ts_example/app/test.ts
This experimental syntax requires enabling one of the following parser plugin(s): "decorators-legacy", "decorators".

**Comment by Soontao** [comment]
thanks for your issue, i'll check it tomorrow  :)

**Comment by Soontao** [comment]
hi @guohai 

I've release a new version `1.2.4` to support decorators of typescript, could you try it in your side?

Regards,
Theo

**Comment by guohai** [comment]
> 

Yes, it works. Thanks @Soontao
