### ISSUE TITLE
TypeScript type declarations not found

### ISSUE THREAD

**Issue by karlhepler** [Soontao/cycle-import-check#7]
I'm importing this into my project and it won't build because tsc states it cannot find the type declarations. `@types/cycle-import-check` does not exist and I noticed that there are actually types already defined in this repo. I think it's just a configuration issue with the published package. I'm not sure.

```
import { scanDirectoryWithResult } from 'cycle-import-check'
```

**ERROR**

![image](https://user-images.githubusercontent.com/791071/111530547-cbfa5b80-8739-11eb-98b6-03c5d63bdc65.png)

**Comment by Soontao** [comment]
let me check about this

**Comment by Soontao** [comment]
@karlhepler 

just upgrade to the new version `1.0.16`, i've renamed the `api.ts` to `index.ts` to match the typescript module scan logic. 

if you want to use the old version of this library, just try the `import {} from "cycle-import-check/lib/api"`

Thanks
